package org.gluu.casa.plugins.consent.ldap;

import com.unboundid.ldap.sdk.ReadOnlyEntry;
import com.unboundid.ldap.sdk.persist.FilterUsage;
import com.unboundid.ldap.sdk.persist.LDAPEntryField;
import com.unboundid.ldap.sdk.persist.LDAPField;
import com.unboundid.ldap.sdk.persist.LDAPObject;
import org.gluu.casa.misc.Utils;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * This class provides an implementation of an object that can be used to
 * represent oxClientAuthorizations objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@LDAPObject(structuralClass="oxClientAuthorizations",
        superiorClass="top")
public class ClientAuthorization {

    // The field to use to hold a read-only copy of the associated entry.
    @LDAPEntryField
    private ReadOnlyEntry ldapEntry;

    // The field used for RDN attribute oxId.
    @LDAPField(inRDN=true,
            filterUsage= FilterUsage.ALWAYS_ALLOWED,
            requiredForEncode=true)
    private String[] oxId;

    // The field used for optional attribute oxAuthClientId.
    @LDAPField(filterUsage= FilterUsage.ALWAYS_ALLOWED)
    private String[] oxAuthClientId;

    // The field used for optional attribute oxAuthScope.
    @LDAPField
    private String[] oxAuthScope;

    /**
     * Retrieves the first value for the field associated with the
     * oxAuthClientId attribute, if present.
     *
     * @return  The first value for the field associated with the
     *          oxAuthClientId attribute, or
     *          {@code null} if that attribute was not present in the entry or
     *          does not have any values.
     */
    public String getOxAuthClientId()
    {
        if ((oxAuthClientId == null) ||
                (oxAuthClientId.length == 0))
        {
            return null;
        }
        else
        {
            return oxAuthClientId[0];
        }
    }

    /**
     * Sets the values for the field associated with the
     * oxAuthClientId attribute.
     *
     * @param  v  The values for the field associated with the
     *            oxAuthClientId attribute.
     */
    public void setOxAuthClientId(final String... v)
    {
        this.oxAuthClientId = v;
    }

    public List<String> getOxAuthScopeAsList() {
        return Utils.listfromArray(oxAuthScope);
    }

}
